/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const TrainingIndexLazyImport = createFileRoute('/training/')()
const TheoryIndexLazyImport = createFileRoute('/theory/')()
const MuslotoIndexLazyImport = createFileRoute('/musloto/')()
const MortgageIndexLazyImport = createFileRoute('/mortgage/')()
const LoginIndexLazyImport = createFileRoute('/login/')()
const CalculatorIndexLazyImport = createFileRoute('/calculator/')()

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TrainingIndexLazyRoute = TrainingIndexLazyImport.update({
  id: '/training/',
  path: '/training/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/training/index.lazy').then((d) => d.Route),
)

const TheoryIndexLazyRoute = TheoryIndexLazyImport.update({
  id: '/theory/',
  path: '/theory/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/theory/index.lazy').then((d) => d.Route))

const MuslotoIndexLazyRoute = MuslotoIndexLazyImport.update({
  id: '/musloto/',
  path: '/musloto/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/musloto/index.lazy').then((d) => d.Route))

const MortgageIndexLazyRoute = MortgageIndexLazyImport.update({
  id: '/mortgage/',
  path: '/mortgage/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/mortgage/index.lazy').then((d) => d.Route),
)

const LoginIndexLazyRoute = LoginIndexLazyImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login/index.lazy').then((d) => d.Route))

const CalculatorIndexLazyRoute = CalculatorIndexLazyImport.update({
  id: '/calculator/',
  path: '/calculator/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/calculator/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/calculator/': {
      id: '/calculator/'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/mortgage/': {
      id: '/mortgage/'
      path: '/mortgage'
      fullPath: '/mortgage'
      preLoaderRoute: typeof MortgageIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/musloto/': {
      id: '/musloto/'
      path: '/musloto'
      fullPath: '/musloto'
      preLoaderRoute: typeof MuslotoIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/theory/': {
      id: '/theory/'
      path: '/theory'
      fullPath: '/theory'
      preLoaderRoute: typeof TheoryIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/training/': {
      id: '/training/'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorIndexLazyRoute
  '/login': typeof LoginIndexLazyRoute
  '/mortgage': typeof MortgageIndexLazyRoute
  '/musloto': typeof MuslotoIndexLazyRoute
  '/theory': typeof TheoryIndexLazyRoute
  '/training': typeof TrainingIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorIndexLazyRoute
  '/login': typeof LoginIndexLazyRoute
  '/mortgage': typeof MortgageIndexLazyRoute
  '/musloto': typeof MuslotoIndexLazyRoute
  '/theory': typeof TheoryIndexLazyRoute
  '/training': typeof TrainingIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/calculator/': typeof CalculatorIndexLazyRoute
  '/login/': typeof LoginIndexLazyRoute
  '/mortgage/': typeof MortgageIndexLazyRoute
  '/musloto/': typeof MuslotoIndexLazyRoute
  '/theory/': typeof TheoryIndexLazyRoute
  '/training/': typeof TrainingIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculator'
    | '/login'
    | '/mortgage'
    | '/musloto'
    | '/theory'
    | '/training'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculator'
    | '/login'
    | '/mortgage'
    | '/musloto'
    | '/theory'
    | '/training'
  id:
    | '__root__'
    | '/'
    | '/calculator/'
    | '/login/'
    | '/mortgage/'
    | '/musloto/'
    | '/theory/'
    | '/training/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculatorIndexLazyRoute: typeof CalculatorIndexLazyRoute
  LoginIndexLazyRoute: typeof LoginIndexLazyRoute
  MortgageIndexLazyRoute: typeof MortgageIndexLazyRoute
  MuslotoIndexLazyRoute: typeof MuslotoIndexLazyRoute
  TheoryIndexLazyRoute: typeof TheoryIndexLazyRoute
  TrainingIndexLazyRoute: typeof TrainingIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculatorIndexLazyRoute: CalculatorIndexLazyRoute,
  LoginIndexLazyRoute: LoginIndexLazyRoute,
  MortgageIndexLazyRoute: MortgageIndexLazyRoute,
  MuslotoIndexLazyRoute: MuslotoIndexLazyRoute,
  TheoryIndexLazyRoute: TheoryIndexLazyRoute,
  TrainingIndexLazyRoute: TrainingIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/calculator/",
        "/login/",
        "/mortgage/",
        "/musloto/",
        "/theory/",
        "/training/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/calculator/": {
      "filePath": "calculator/index.lazy.tsx"
    },
    "/login/": {
      "filePath": "login/index.lazy.tsx"
    },
    "/mortgage/": {
      "filePath": "mortgage/index.lazy.tsx"
    },
    "/musloto/": {
      "filePath": "musloto/index.lazy.tsx"
    },
    "/theory/": {
      "filePath": "theory/index.lazy.tsx"
    },
    "/training/": {
      "filePath": "training/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
